apiVersion: v1
kind: Pod
metadata:
  name: multi-container-demo
spec:
  volumes:
    - name: shared-volume
      emptyDir: {}
  containers:
    - name: container-1
      image: nginx
      volumeMounts:
        - name: shared-volume
          mountPath: /var/www/html
    - name: container-2
      image: busybox
      command: ["sh", "-c", "while true; do echo 'Hello from container-2'; sleep 10; done"]
      volumeMounts:
        - name: shared-volume
          mountPath: /var/www/html


